name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: tenjaa
        password: ${{ secrets.docker_password }}
        repository:  tenjaa/concourse-github-app-token
        tag_with_sha: true
